=== clicksounds/clicks/pack.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://clicksounds.github.io/clicks/pack.schema.json",
  "title": "Click Pack",
  "description": "A Pack of Clicks!",
  "type": "object",
  "properties": {
    "$schema": {
      "$comment": "Shows what options are possible, and what options are required. Do not delete this",
      "type": "string",
      "description": "The click pack metadata schema URL. Please do NOT remove this."
    },
    "id": {
      "description": "The ID of the click pack. goes in the format of \"{username}.{name},\" (excluding the comma at the end). username being the name you go by online, and name being the name of this click pack. There is a pattern you have to match which is: lowercase letters allowed, numbers are allowed, hyphens/dashes allowed, and one period (as a seperator from the author and name).",
      "examples": [
        "myname.myclickpack"
      ],
      "type": "string",
      "pattern": "^([a-z0-9\\-]+\\.[a-z0-9\\-]+)$"
    },
    "version": {
      "description": "The version of the click pack. This is used to determine if the pack has been updated, and should be incremented by 1 when the pack is updated.",
      "type": "integer",
      "minimum": 1
    },
    "packgen": {
		  "type": "boolean",
		  "description": "Indicates if a pack was made using pack generator. This is important for debugging. It must be enabled only on click packs made using pack generator."
	  },
    "packcon": {
      "type": "boolean",
      "description": "Indicates if a pack was made using pack converter. This is important for debugging. It must be enabled only on click packs made using pack converter."
    },
    "type": {
      "description": "Is this click pack a Meme, or is it Useful. Only allows \"Useful\" or \"Meme\" to be typed. (CASE SENSITIVE)",
      "type": "string",
      "pattern": "^(Meme|Useful)$"
    },
    "name": {
      "description": "The name of the click pack. Should not include the words clicks, releases, or pack. Also special characters EXCEPT ' and - are blocked.",
      "type": "string",
      "minLength": 2,
      "pattern": "^(?![a-zA-Z0-9 '-\\?\\!]*?click|[a-zA-Z0-9 '-\\?\\!]*?pack|[a-zA-Z0-9 '-\\?\\!]*?release)[a-zA-Z0-9 '-\\?\\!]*?$"
    },
    "description": {
      "description": "Up to 150 character description of the click pack, optional.",
      "type": "string"
    },
    "authors": {
      "description": "The authors of the click pack. First author listed is considered the main author.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the author",
            "type": "string"
          },
          "gdAccountID": {
            "description": "If you put a Geometry Dash ACCOUNT ID here, people will be able to click your name to open up for Geometry Dash profile.",
            "type": "number",
            "exclusiveMinimum": 0
          },
          "type": {
            "description": "The type of author. Currently can by \"Main\" (default), \"Provider\", or \"Requester\".\nREAD: if you are just providing the sounds, and it's not made by you, then put yourself as the provider and list the author that made the original sound first, AND EITHER PUT \"Main\" FOR THEM OR DON'T USE TYPE FOR THEM.",
            "type": "string",
            "pattern": "^(Main|Provider|Requester)$",
            "examples": [
              "Main",
              "Provider",
              "Requester"
            ]
          },
          "additionalProperties": false
        },
        "required": ["name"]
      }
    },
    "click-files": {
      "description": "All of the click file names for the pack (without the folder name nor the file extension), fills out automaticly if it's accepted on to the clicks index.",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "releases-files": {
      "description": "All of the release file names for the pack (without the folder name nor the file extension), fills out automaticly if it's accepted on to the clicks index.",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "additionalProperties": false
  },
  "required": ["id", "name", "authors", "type"]
}

=== clicksounds/clicks/Useful/baguettegun.aula-f75-pack/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "baguettegun.aula-f75-pack",
    "packcon": true,
    "type": "Useful",
    "name": "Aula F75 Pack",
    "description": "Brah",
    "authors": [
        {
            "name": "BaguetteGun",
            "gdAccountID": 38327293
        }
    ]
}

=== clicksounds/clicks/Useful/luke.lukes-toy-gun/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "luke.lukes-toy-gun",
    "version": 1,
    "packgen": true,
    "type": "Useful",
    "name": "Lukes Toy Gun",
    "description": "Cut by Beat from Click Sounds Geode",
    "authors": [
        {
            "name": "Luke",
            "gdAccountID": 39021138
        }
    ]
}

=== clicksounds/clicks/Useful/ciganxxx.logitech-g-pro/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "ciganxxx.logitech-g-pro",
    "packgen": true,
    "type": "Useful",
    "name": "Logitech G PRO Keyboard",
    "description": "Unknown",
    "authors": [
        {
            "name": "CiganXXX",
            "gdAccountID": 32285568
        }
    ]
}

=== clicksounds/clicks/Useful/unknown.cherrymx-linear/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "unknown.cherrymx-linear",
    "version": 1,
    "packgen": true,
    "type": "Useful",
    "name": "cherrymx linear",
    "authors": [
        {
            "name": "unknown",
            "gdAccountID": 39709158
        }
    ]
}

=== clicksounds/clicks/Useful/beat.bubbly-pops/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "beat.bubbly-pops",
    "packgen": true,
    "type": "Useful",
    "name": "Bubbly Pops",
    "description": "Former default pack of the Click Sounds mod. Made with help from zxset.",
    "authors": [
        {
            "name": "Beat",
            "gdAccountID": 13873867
        }
    ]
}

=== clicksounds/clicks/Useful/nicnicboss.nicnicboss-logitech-g502-v2/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "nicnicboss.nicnicboss-logitech-g502-v2",
    "version": 2,
    "packgen": true,
    "type": "Useful",
    "name": "NicNicBoss Logitech G502 V2",
    "description": "remake of nicnicboss g502!",
    "authors": [
        {
            "name": "NicNicBoss"
        }
    ]
}

=== clicksounds/clicks/Useful/nicnicboss.nicnicboss-razer-basilisk-v3/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "nicnicboss.nicnicboss-razer-basilisk-v3",
    "version": 1,
    "packgen": true,
    "type": "Useful",
    "name": "NicNicBoss Razer Basilisk V3",
    "authors": [
        {
            "name": "NicNicBoss"
        }
    ]
}

=== clicksounds/clicks/Useful/fluffyzeo.vxe-r1-pro-max/pack.json
{
    "$schema": "https://clicksounds.github.io/clicks/pack.schema.json",
    "id": "fluffyzeo.vxe-r1-pro-max",
    "packgen": true,
    "type": "Useful",
    "name": "VXE R1 Pro Max",
    "description": "Mouse: VXE (aka VGN) R1 Pro Max (Kailh White Sword switches); use ZCB to get the full pack with 97 sounds; Credit: zeo (fluffyzeo on discord)",
    "authors": [
        {
            "name": "fluffyzeo"
        }
    ]
}
